### ISSUE TITLE
lexical score?

### ISSUE THREAD

**Issue by tommycarstensen** [biopragmatics/biomappings#119]
What is the `lexical score` in this file?
biomappings/src/biomappings/resources/predictions.tsv

I couldn't readily find the explanation in neither the README nor the source code.

Thanks a million!

**Comment by cthoyt** [comment]
The score column itself is reported by the method used to generate the predicted mapping. The "type" column gives a high-level hint on the kind of method, which for most predictions is `lexical`, but the "source" column is the best way to learn more since it usually points to the script that was used to generate the mapping. Most of these scripts are in https://github.com/biopragmatics/biomappings/tree/master/scripts.

For most of the lexical mappings, they were generated using `Gilda`. Depending on the script, the score therefore refers to either:

1. The Gilda match score, inspired by https://aclanthology.org/W15-3801/. Section 5.2 of the [supplementary material for the [Gilda paper](https://doi.org/10.1093/bioadv/vbac034) describes this score in detail, where 1.0 is best and 0 is worst. https://github.com/biopragmatics/biomappings/blob/master/scripts/generate_agrovoc_mappings.py is an example that uses this variant
2. A high-level estimation of the precision of the scores generated by the given script. For example, the CL-MeSH mappings were estimated to be 90% correct, so all of the mappings generated by https://github.com/biopragmatics/biomappings/blob/master/scripts/generate_cl_mesh_mappings.py are marked with 0.9 as its score
